#pragma kernel CSMain

float _BrushRange;
float3 _BrushPosition;
float4 _BrushColor;

RWStructuredBuffer<float4> _VoxelColors;

float3 _Scale;
uint _Width, _Height, _Depth;


[numthreads(8, 1, 8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	int idx = id.x + id.z * _Width;
	float2 position = float2(id.x * _Scale.x, id.z * _Scale.z);
	float dist = distance(position, _BrushPosition.xz) - _BrushRange;

	if (dist <= 0)
		_VoxelColors[idx] = _BrushColor;
}

